### ISSUE TITLE
Ratio Page not loading

### ISSUE THREAD

**Issue by paranoidloyd** [Murnto/FactorioData-dlang#11] opened 2017-07-11 15:34 UTC
Can't get the ratio page to load, tested in Chrome and Edge, Edge returns the error:

This content can’t be shown in a frameThere is supposed to be some content here, but the publisher doesn’t allow it to be displayed in a frame. This is to help protect the security of any information you might enter into this site.
--

**Comment by DRY411S** [comment] 2017-07-11 16:11
Confirmed in Chrome, although the page just fails silently (no content, no error message)

**Comment by Murnto** [comment] 2017-07-18 10:21
If by ratio page you're referring to factoratio, it loads fine for me.

Is this still occurring? The server hosting this changed around a week ago (and has since switched back).

**Comment by DRY411S** [comment] 2017-07-18 11:09
Is now loading for me too. Was not, presumably a Chrome browser issue that has been fixed by an update.

**Comment by Murnto** [comment] 2017-07-20 05:09
@paranoidloyd is it loading for you now?

**Comment by DRY411S** [comment] 2017-07-20 05:15
When @paranoidllyod reported this, I came here to report it too, and added my report to this (for Chrome). At that time I also checked that I got the issue with IE. I did. I do not anymore.

I also checked it on Safari on my iPad, which also had the same problem. It doesn't any longer.

I guess that suggests the issue was down to your hosting server change.

**Comment by Murnto** [comment] 2017-07-20 05:33
Alright then, I'll close this then :)

**Closed as completed by Murnto** 2017-07-20 05:33 UTC
